routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
*/

Auth::routes(['verify' => true]);

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'verified'], function () {
    Route::get('/', 'HomeController@index')->middleware('auth');

    // RESOURCES
    Route::resource('profile', 'ProfileController');
    Route::resource('users', 'UsersController');

    // GETS
    Route::get('bo/get-user', 'BOService@getUser');
    Route::get('bo/get-users', 'BOService@getUsers');
});

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
*/

resources/views/get-ready.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <section class="blur-container">
            <div class="blur"></div>

            <div class="card card-default">
                <div class="card-heading">Set a password</div>

                <div class="card-body">
                    {{-- Form --}}
                    <form action="{{ route('profile.update', $id) }}" method="post">
                        {{ method_field('PUT') }}

                        <input type="hidden" name="tab" value="password">

                        {{-- Password --}}
                        <div class="form-group {{ $errors->has('password') ? ' has-error has-feedback' : '' }}">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" id="password" name="password"
                                   placeholder="Password" required>

                            @if ($errors->has('password'))
                                @include('components.error', ['errors' => $errors->get('password')])
                            @endif
                        </div>
                        {{-- End Password --}}

                        {{-- Confirm Password --}}
                        <div class="form-group {{ $errors->has('confirm-password') ? ' has-error has-feedback' : '' }}">
                            <label for="confirmPassword">Confirm Password</label>
                            <input type="password" class="form-control" id="confirmPassword"
                                   name="confirm_password" placeholder="Confirm Password" required>

                            @if ($errors->has('confirm-password'))
                                @include('components.error', ['errors' => $errors->get('confirm-password')])
                            @endif
                        </div>
                        {{-- End Confirm Password --}}

                        {{-- Actions --}}
                        <section id="actions" class="float-right">
                            <button type="submit" class="btn btn-primary">Setup</button>
                        </section>
                        {{-- End Actions --}}
                    </form>
                    {{-- End Form --}}
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.api')

@section('css')
@endsection

@section('content')
@endsection

@section('js')
@endsection